apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    color: red
spec:
  containers:
    - image: janakiramm/color
      name: red
      env:
        - name: "COLOR"
          value: "red"
      ports:
        - containerPort: 8080
