apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  selector:
    color: red
  type: NodePort
  ports:
   - name: http
     nodePort: 31001
     port: 80
     targetPort: 8080
     protocol: TCP
